"""Create all tables

Revision ID: 0dfbcbdb7a81
Revises:
Create Date: 2025-03-16 19:49:53.180437

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0dfbcbdb7a81"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("username", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=250), nullable=False),
        sa.Column(
            "address",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("phone", sa.String(length=100), nullable=True),
        sa.Column("website", sa.String(length=100), nullable=True),
        sa.Column(
            "company",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
        sa.UniqueConstraint("email", name=op.f("uq_user_email")),
    )
    op.create_table(
        "post",
        sa.Column("userId", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column(
            "body", sa.Text(), server_default="", nullable=False
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["userId"], ["user.id"], name=op.f("fk_post_userId_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_post")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("post")
    op.drop_table("user")
    # ### end Alembic commands ###
